name: Packages Test
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    name: test packages
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
          source-url: https://nuget.pkg.github.com/marcosbergami/index.json
        env:
         NUGET_AUTH_TOKEN: ${{secrets.PACKAGES_TOKEN}}
      - run: dotnet build
